### ISSUE TITLE
BN-498 ⁃ [Test] Check the size of fixed length fields when encoded to JSON

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#1041]
Due to our use of VLQ, we sometimes accidentally put too little information into JSON when we rely on the serialization. This was identified by Nick's "fix" to BloomFilter which while it now passes the tests, no longer encodes 256 bytes of information into the JSON body of a block. This is alright for the serialization scheme because VLQ encoded extra information about the data it left off (probably a bunch of leading zeros) but in the JSON we don't have this. Therefore, for fields where we expect to there to be a fixed length of Base58 encoded byte data, we should ensure that we do not accidentally cut off data.

## Acceptance Criteria
* An issue with the existing encoders/decoders is identified and fixed, or it is confirmed that there are no issues with the encoders/decoders

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/BN-498) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
@b-vennes Please connect with James on this ticket
