### ISSUE TITLE
Update chain selection mechanism to look at height

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#1042]
I believe I am running into a diverging network on Hel when I allow one node to forge a chain longer than `maxInv` (or whatever that maximum comparison length is), then if you attempt to bring another node online but start it forging before it gets fully sync'd up, then a block can get forged locally beneath the depth of the comparison length. This results in the new node starting to forge on a fork and being unable to sync with the chain.

This can be eliminated now that we have the block height contained in the header since we no longer have to try to locally guess what the heights are of the chain that is being broadcast to us. 

We can avoid the problem for now by being careful about when we start nodes forging.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-834) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
This will be addressed in Tetra
