### ISSUE TITLE
BN-502 ⁃ Integration Test CI/CD

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1115]
While unit testing is automated on code pushes, integration testing is currently a manual/local process.  Integration tests can instead be run in GitHub Actions.  This will lead to more stable and predictable runs of integration tests using a predictable environment.

Acceptance Criteria:

* Integration Tests run automatically on pushes to the `main` branch.  (Integration Tests should be able to run manually in CI/CD on branches as well)
* Integration Tests run using GitHub Actions

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/BN-502) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
@Tuxman Please connect with James on this ticket
