### ISSUE TITLE
Empty String apiKeyHash Not Interpreted as None

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1130]
The HttpService class uses an optional `apiKeyHash` to determine if requests should use API key authorization.  The default value in the configuration is `""` (presumably intended to be the equivalent of None or null).  But since this value can technically be Base58-decoded, HttpService enables authorization but no requests will be properly authorized.

Bifrost should instead assume that authorization is always enabled, unless a (new) flag indicates that it should explicitly be disabled.  This means that an `apiKeyHash` value must either be provided, or a (new) flag `authEnabled` must be set to `false`.  The base application.conf should remove or comment out the line `apiKeyHash = ""` to make it `null`.  If it is never overridden in a custom configuration and if a command line option is not provided, then the node should crash/terminate at startup.

Acceptance Criteria:
- Bifrost authorization is enabled by default
- Bifrost authorization can be disabled when desired (like local environments)
- When authorization is enabled, an `apiKeyHash` is also required.  A default should _not_ be provided in configuration.

**Comment by scasplte2** [comment]
I like the idea of handling the rejection better if nullifying the apiKeyHash would help with that. To be honest, I never found how to provide a None value into config except for not including it.

The behavior I would like to keep is that by default I would like the API turned off. Having an empty string compared to any hash output was the quickest way to ensure that.
