### ISSUE TITLE
Document Error Handling Best Practices

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1138]
In various locations in the code, exceptions are thrown when some sort of error is encountered.  Throwing an exception is relatively expensive because stack traces need to be generated which requires the ability to "unwind" the code, thus reducing the compiler's ability to optimize.  For similar reasons, it also makes it more difficult for humans to reason about the various code paths.  Exceptions should be treated exceptionally, meaning they should only really be thrown or used if something  completely "unexpected" happens.

Throwing exceptions also forces consumers of a library/code to understand the details of what can fail inside of the library.  This is a domain leak since internal implementation details leak across interface boundaries.

An improvement from this is to wrap unsafe operations in a `scala.util.Try` and return the Try result.  This allows library consumers to know that a call could potentially fail and instructs developers that they need to handle the potential failure in a functional way.

But `Try` still suffers from lack of type safety around the failure/exception/throwable.  A `Failure` contains any type of `Throwable` which includes a virtually infinite number of error cases.  This still allows for the domain leaks mentioned above.

`scala.util.Either` can be used instead.  An Either can be one of `Left` or `Right`.  The Scala community has standardized on the pattern of treating `Right` as a successful/happy path, and `Left` as an unsuccessful/unhappy path.  This pattern can be thought of in a similar manner as `scala.util.Try`, but the main difference is that the `Left` case of `Either` can use explicit types while a `Failure` case of a `Try` can't.

Generally, library authors define an algebraic data type to represent the possible known error conditions, and these become a part of the public interface/contract.  (In other words, it looks like a `sealed trait MyLibraryError` with several `case class SomeSpecificError() extends MyLibraryError`).  Once defined, the interface methods have a return type `Either[MyLibraryError, SomeSuccessResult]`.

This pattern will also allow us to better integrate with and leverage [Cats](https://typelevel.org/cats/).

### Error Conditions
Error conditions exist in any application, but capturing and presenting those errors is an explicit task.  Well-defined error conditions allow for more "completeness" in an application's code.  Error conditions can come in a wide variety, but the ones most applicable to us are:

* Invalid input
* Temporary runtime errors

In Scala, we can define an algebraic data type to represent the potential error conditions for some class or file or package.  There is no strict rule-of-thumb for the level of granularity or scope of an error ADT.  For this ticket, evaluate the various locations in the codebase where things can "fail".  Wherever there is a logical grouping of error conditions related to some task, create a new `sealed trait SomeErrorType`.  If possible, define sub-types of `SomeErrorType` to capture each of the knowable error conditions.  However, we will not _use_ these new types quite yet, so it is okay if some (or many) error implementations can't be defined yet.

For example, the `BlockValidator.scala` file defines a `BlockValidator` and a couple different BlockValidator implementations.  These implementations make use of `require` to perform data validation.  There could be a `sealed trait BlockValidatorError` and  the individual `require` statements can have a corresponding BlockValidatorError sub-type.

Acceptance Criteria:

* Error conditions in the codebase are audited and logical groupings are identified
* Logical groupings of error conditions have a corresponding "error" trait
* Known error conditions have implementations of those "error" traits

### Refactor `throw` in Class Constructors
Throwing exceptions incurs a performance penalty and can lead to unexpected runtime behavior.  This is particularly unexpected in class constructors.  The use of `require` in class constructors can have the side-effect of a thrown exception.  We should avoid these exceptions during class construction.

A strategy to do this is to make the class constructor private (i.e. `class MySpecialClass private (a: String) {}`) and use a companion object for defining helper constructors.  These helper companion constructors pre-validate the data (performing similar behavior to the `require` method) and return an `Either`  (i.e. `def apply(a: String): Either[SomeError, MySpecialClass]`).  If the data is valid and a `MySpecialClass` can successfully be created, then a `Right` is returned.  If the data is invalid, a `Left` is returned.

A later ticket will replace the use of `require` with `cats.data.Validated`.  For now, preserve the use of `require` in the helper constructors, but wrap them in a `Try`, transform to an Either, and capture the IllegalArgumentException as an explicit error type case class from the error ADTs defined in a previous ticket.

Acceptance Criteria:

* Class constructors no longer throw exceptions
* Class constructors that could throw exceptions have their constructors marked private
* Class constructors that require data validation have corresponding companion object helpers that perform the validation and return `Either`

### Refactor `throw` in Methods
Throwing exceptions incurs a performance penalty and leads to unexpected runtime behavior.  Instead of throwing an Exception, the error condition should be captured in an explicit data type, and a Left should be returned instead.

In methods where `throw` is used, change the return type from `T` to `Either[SomeErrorType, T]`.  Where `throw` is used, instead return a `Left[SomeSpecificErrorType]` instead.  If everything is successful, return a `Right[T]`.

In cases where `require` is used, wrap the call(s) in a `Try`, transform `.toEither`, and map the Left throwable into a specific error type.

Acceptance Criteria:

* Methods no longer "throw" exceptions
* Methods that previously threw exceptions have a return signature `Either[SomeError, T]`

### Refactor `require` and `ensuring`
Scala offers `require` and `ensuring` as helpers for a "design-by-contract" approach.  However these helpers come with the consequence of throwing exceptions.  The Cats library offers a more functional and deterministic way of validating data called `cats.data.Validated`.  It adopts a pattern similar to `Either`, but the `Left` case is meant to accumulate multiple errors.

Acceptance Criteria:

* Instances where we use `require` or `ensuring` are replaced with the `cats.data.Validated` pattern

See:

* [Cats Validated](https://typelevel.org/cats/datatypes/validated.html)

### Return Either instead of Try
`scala.util.Try` is an effective method for providing code safety in a functional manner; however, the unbounded number of types of `Throwable` puts a heavy burden of a consumer of that `Try`.

`Try` can still be used in the codebase, but wherever possible, they should be transformed into an `Either` with explicit error conditions returned in the `Left` case.

`private` methods are still welcome to return `Try`.  Only "public" methods should be concerned with this change.  If a public method returns `Try` but doesn't _need_ to be public, you can simply make it private.

Acceptance Criteria:

* Public methods which return `Try` should instead return `Either` where possible
* Where not possible, the code is documented with a reason why

### Enforce Non-Empty Collections
The Scala standard library offers many types of collections which can contain 0 or more items.  However, certain operations like `.head`, `.last`, and `.reduce` require the collection to contain at least one item.

The Cats library offers a new type of collection called a `Chain` (which is like a List but with fast append and prepend characteristics).  Additionally, Cats has a `NonEmptyChain` which is a Chain that is guaranteed to have at least one item.

In cases in our codebase that assume an input collection has at least one item, change the signature to accept a `NonEmptyChain`.  This will likely require signature changes in many places in the codebase.  It will also require validation somewhere along the way to transform a Seq/List into a NonEmptyChain (or a Left if empty).

Acceptance Criteria:

* Uses of Scala collections that our application logic expect to be non-empty are refactored to use `NonEmptyChain` instead
* `.head`, `.last`, and `.reduce` are only ever called on a NonEmptyChain.

See:

* [Cats Chain](https://typelevel.org/cats/datatypes/chain.html)

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-846) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
@SeanCheatham Please connect with James about this ticket
