### ISSUE TITLE
Document Lazy Val Best Practices

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1146]
Lazy evaluation is a very important concept in functional programming.  It also offers a big performance advantage in cases where data may not need to be computed in short-circuiting cases.

However, `lazy val` are less performant than eager {{val}}s because the compiler introduces synchronization code to ensure that a lazy val is only evaluated once in multi-threaded environments.  As such, excessive use of lazy vals can decrease performance if the synchronization cost outweighs the compute cost.

In general, the use of a lazy val should be reserved for expensive computations and initialization dependencies.  But for general-purpose usage, they should be avoided.  If a `lazy val` is expensive but only ever expected to be referenced one time, it can be turned into a `def` instead.  If a `lazy val` is computationally or memory inexpensive, it can be turned into a simple `val`.

Acceptance Criteria:

* A Confluence document and/or learning material exists for lazy val best practices

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-847) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
@SeanCheatham Please connect with James about this ticket
