### ISSUE TITLE
Integration test for creation of all Transfer types through the API

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#1190]
I am currently encountering an issue with the Poly Transfer `createRaw` transaction where the changeAddress box is not getting added to the list. I am going to fix the bug but these are the sorts of things I expect to be found by testing.  So my initial idea is that we hardcode some transaction data and test that we get back the exact expected result, in addition to doing the randomized testing that we are doing now.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-851) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
Already addressed
