### ISSUE TITLE
Test the new implementation of JDK on MacOS

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#120]

**Comment by yamir1995** [comment]
Works and runs fine; IntelliJ is unable to locate the graalvm package from Oracle so it looks there are compiling issues, but it still compiles and runs fine when I execute. Looking into updating IntelliJ to a newer version to see if that fixes it.

**Comment by yamir1995** [comment]
Updated to IntelliJ 2018 and it works fine now
