### ISSUE TITLE
Test ConsensusStorage's compatibility with main branch

### ISSUE THREAD

**Issue by jingsting** [Topl/Bifrost#1201]
Test one:
- Start with main branch and forge on A
- start with forger-refactor and sync up on B
- switch A to forger-refactor branch and copy consensus data over from B
- print out consensus parameters and start forging on A

Test two:
- Start with main branch and forge on A, at the same time start with forger-refactor on B
- switch A to forger-refactor branch and copy consensus data over from B
- print out consensus parameters and start forging on A

**Comment by jingsting** [comment]
Both tests were successful

**Comment by scasplte2** [comment]
Test the behavior when you attempt to bootstrap a 1.3.4 node to a 1.3.7 node (forger-refactor)

**Comment by jingsting** [comment]
Test three (bootstrap a 1.3.4 node to a 1.3.7 node (forger-refactor)):

Start with forger-refactor branch and forge on A
start with main branch on B and sync up to A
switch A to forger-refactor branch and copy consensus data over from B
print out consensus parameters and start forging on B

Test four (resume a forger-refactor without consensus data):

Start with forger-refactor branch and forge some blocks
Stop the node, and delete the consensus data
Resume the node (a new consensus data was initialized, since we don't update the parameters yet, the node was able to forging without problem)
