### ISSUE TITLE
Identify functionality of currently implemented bloom filter and research what needs to be done for general transaction bloom filter

### ISSUE THREAD

**Issue by yamir1995** [Topl/Bifrost#123]

**Comment by yamir1995** [comment]
- Attempted to imitate bloom filter functionality currently implemented for contract completion transactions. Unable to debug errors that occurred when replicating for asset creation transaction (issue seemed to be that the transaction bloom topics were not being stored in the block's bloom topics correctly)

**Comment by scasplte2** [comment]
Bloom filter was refactored in Dion upgrade
