### ISSUE TITLE
Extend RPC api format from contracts and assets to wallet as well

### ISSUE THREAD

**Issue by yamir1995** [Topl/Bifrost#128]
- At the same time, use annotations used in the wallet api to allow swagger to recognize all api routes (contracts and assets as well)

**Comment by yamir1995** [comment]
- New keyfiles generated during wallet RPC tests need to be deleted to prevent breaking other tests locally
- Tests on CircleCI continue to break though, needs to be debugged

**Comment by yamir1995** [comment]
- Tests passing
- Need to decide what to deprecate
- Currently, poly transfer implemented in wallet and asset api routes while arbit and asset transfers are in the asset route

**Comment by scasplte2** [comment]
this has been completed.
