### ISSUE TITLE
Keyfile Definitions and AES for Ed25519

### ISSUE THREAD

**Issue by b-vennes** [Topl/Bifrost#1322]
## Description

We need to be able to encrypt and decrypt secrets using Keyfiles for Ed25519.

## Acceptance Criteria

- Keyfiles can be encrypted/decrypted for Ed25519 private keys
- Unit tests are added for the new keyfile and companion classes/objects

**Comment by jingsting** [comment]
Ed25519 was tested by:
changing the keyRing used everywhere to take Ed25519 instead of Curve25519 in the branch: test-ed25519
signing transactions with Ed25519 signature scheme in BramblJs and broadcasting them
