### ISSUE TITLE
BN-508 ⁃ Functional Byte Serialization/Deserialization

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1336]
Bifrost data is currently serialized in a procedural manner.  `Writers` implement a side-effecting operation which mutates an internal buffer.  While mutability provides performance gains, those details can be abstracted away from implementers.  The Bifrost Serialization mechanism should be refactored such that serialization is defined as concrete steps, and the resulting byte array is only realized when needed.

Acceptance Criteria:

* Bifrost Serialization's uses a functional interface

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/BN-508) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
Something that might be useful to think about as you go through this is
considering the amount of byte arrays in memory. It may take a more
concerted effort to actually optimize but I am just thinking back to lhe
VisualVM you showed a few weeks back and my surprise that we had 30 MB of
bytes arrays in memory at once.
