### ISSUE TITLE
Review Bifrost Api Routes & Transactions Spec

### ISSUE THREAD

**Issue by yamir1995** [Topl/Bifrost#137]
- Review bifrost api routes spec format and information
- Consider adding a list of all transactions to the spec
- Consider adding instructions/steps for testing any new transaction that is created - same or new spec?

**Comment by yamir1995** [comment]
Here is a link to the spec in the Google Drive: https://docs.google.com/document/d/1BlwQq0lpmoSV89fYVYcBP0mxBCETttPyFaI7QOslt3w/edit

**Comment by scasplte2** [comment]
completed in v0.3
