### ISSUE TITLE
Network message optimization

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#1383]
We need to optimize the handling of messages when a node extends their chain. Currently every block creates a deluge of message sthat may or may not be wanted or needed. We should look at and understand Cardano's Ouroboros network spec

![image.png](https://images.zenhubusercontent.com/5b1444ebb709d02140684bb7/8ead12a0-feff-4a67-a672-43a220751e94)

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-822) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
Not enough detail
