### ISSUE TITLE
BN-509 ⁃ Remove Attestation's Dependency on KeyManagement

### ISSUE THREAD

**Issue by b-vennes** [Topl/Bifrost#1406]
## Description
The `Key Management` project should be a separated from `Attestation` with `Key Management` being dependent on `Attestation`, but `Attestation` not being dependent on `Key Management`. In order to achieve this, the `Proof` and `Proposition` files in `Attestation` will need to be re-worked to lose their dependencies on the private key implementations in `Key Management`.

## Acceptance Criteria
* the `Key Management` project is a top-level directory in the `common` project
* `Attestation` has no knowledge of specific signature implementations

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/BN-509) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
I have some work done on this @b-vennes , lets talk tomorrow sometime
