### ISSUE TITLE
Fix Genesis Initialization In Hel, Valhalla, and Toplnet

### ISSUE THREAD

**Issue by b-vennes** [Topl/Bifrost#1416]
## Description

Running a node with a Hel, Valhalla, or Toplnet genesis block causes the following error:

`Failed to initialize genesis due to error: requirement failed: MALFORMED GENESIS BLOCK! The calculated genesis block with id 25T1GTRiLRTEJHpuNgkrUk2UKC7bjzv8bPPScBGT3TiBp does not match the required block for the chosen network mode.`

Bug is likely due to a change with `ModifierId` creation in `ModifierId.scala` or `Block.scala`.

**Comment by scasplte2** [comment]
Please be careful about changing that hash that is hard coded. I'd like to
avoid doing that if possible.
