### ISSUE TITLE
[Spike] Investigate Hosted Logging

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1424]
Topl hosts nodes for Toplnet, Valhalla, and Hel networks.  We do not have a straightforward way to access the application logs for these hosted nodes.  Debugging requires SSH access and terminal navigation which limits our ability to debug production issues.

We should investigate ways to surface the application logs in a way that they are accessible to Topl engineers.

### Acceptance Criteria:
- A plan (tickets) exist to make hosted node logs accessible to engineers

**Comment by scasplte2** [comment]
Hosted nodes are now sending their logs to the central GrayLog service
