### ISSUE TITLE
[Spike] Investigate Monitoring Solutions

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1425]
Systems produce various operational metrics as they run.  For example, a machine's CPU and memory usage statistics are helpful when investigating production issues.  Custom metrics can also exist, for example "# of blocks forged".

The ability for engineers to access these metrics is crucial for debugging purposes.  We should investigate what metrics are needed and how to present them to Topl engineers.

Acceptance Criteria:
- A plan (tickets) exists to expose hosted (Toplnet/Valhalla/Hel) Bifrost metrics to Topl engineers

**Comment by scasplte2** [comment]
Hosted nodes are now sending their logs to the central GrayLog service which has been demoed to the team and access provided.
