### ISSUE TITLE
[spike] Test Coverage Reports

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1434]
Unit tests are meant to provide low-level input/output testing for software.  Unit test coverage indicates the percentage of code in the codebase that gets executed during unit testing.  Coverage reports are exportable documents which visually show which class methods and their code branches were executed over the course of a suite of unit tests.

Acceptance Criteria:
- Investigation into generating coverage reports in SBT/Scala projects
- Investigation into failing an SBT build when coverage does not meet a % threshold
- Investigation into publishing coverage reports for each CI/CD build

**Comment by scasplte2** [comment]
@Tuxman can you add an update here with the result of your tests?
