### ISSUE TITLE
Make 127 Length latin-1 metadata value class for AssetValue

### ISSUE THREAD

**Issue by jingsting** [Topl/Bifrost#1471]
We check the length and characters on the metadata string now in SyntacticallyValidatable, we should have a value class enforcing the requirements on metadata

**Comment by SeanCheatham** [comment]
This requirement also applies to `TransferTransaction#data`.

The value class will guarantee the "Syntactic Validation" of these data fields, meaning the length and Latin-1 checks could be removed from `SyntacticallyValidatable`.
