### ISSUE TITLE
KES Scheme Spec

### ISSUE THREAD

**Issue by aaronschutza** [Topl/Bifrost#1485]
A more thorough description of the key evolving scheme is required to list all the different possible configurations of compositions.  The MMM paper specifies a particular parameterization called the asymmetric product composition.  This is only one of many possible compositions and a simpler case is likely to be used for more space efficiency in block headers.  The sum composition is simpler and more compact but limited in the number of time steps to powers of two with constant key and signature length.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-931) by [Unito](https://www.unito.io)

**Comment by aaronschutza** [comment]
I have begun writing a document specifying all the available configurations of the MMM construction that may be used as operational KES keys.

**Comment by aaronschutza** [comment]
https://topl.atlassian.net/wiki/external/296419360/YzNjYzY2NmQ4YWYxNDY5MmE0ZmViNmY4ZGU3YjAyMzc?atlOrigin=eyJpIjoiOTE2Y2EyYzQ1OWUyNDY2OWJlYTcwMTAxYTA0ZDAyMzgiLCJwIjoiYyJ9

Different kinds of keys are now available in the MMM.scala and this document covers details of the implementation and how the proposed address scheme couples with the KES scheme.

**Comment by scasplte2** [comment]
temp reopening so I can sync
