### ISSUE TITLE
As a Bifrost node operator, I want to be able to cryptographically verify the selection of slot leaders in order to ensure I'm engaging in a fair and secure consensus protocol.

### ISSUE THREAD

**Issue by mpk2** [Topl/Bifrost#15]
The PoS scheme that we're using to-date has several holes in it, allowing attackers to abuse "Nothing-At-Stake" issues (and, most likely, others). Ouroboros Praos introduces the concept of epochs and slots -- but slots are randomly assigned leaders. Distributed randomness calculation is itself fraught with challenges, but the 2-HashDH V-OPRF scheme seems like it is a good candidate in the face of malicious key generation.

**Comment by scasplte2** [comment]
Two papers I found on 2-HashDH V-OPRF 

https://eprint.iacr.org/2017/363.pdf
https://eprint.iacr.org/2016/144.pdf

**Comment by scasplte2** [comment]
This is an issue that @aaronschutza has been addressing and is currently testing using his simulation.
