### ISSUE TITLE
[Spike] akka-stream Peer Management

### ISSUE THREAD

**Issue by SeanCheatham** [Topl/Bifrost#1523]
The PeerConnectionHandler manages the TCP events for a TCP connection to a particular other peer in the overall network.  It does so using message low-level Actor messaging, requiring the actor to manage TCP connection open and close events.

akka-stream offers a mechanism which [abstracts](https://doc.akka.io/docs/akka/current/stream/stream-io.html) away almost all of the TCP connection state and allows the developer to focus purely on the exchange of data/bytes.

### Acceptance Criteria
* Is it feasible to leverage akka-stream for peer connection handling?
* If so, create a plan/tickets for the refactor.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-792) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
if you wanted to pursue this with our current set of messages (instead of
incorporating all the OB stuff), I think that would be beneficial if
possible to do in the near future.
