### ISSUE TITLE
SLIP-0023 Cardano Icarus master node derivation

### ISSUE THREAD

**Issue by b-vennes** [Topl/Bifrost#1526]
## Description

Implement [SLIP-0023 Cardano Icarus master node derivation](https://github.com/satoshilabs/slips/blob/master/slip-0023.md) so that key pairs will be compatible with all wallets that currently accept cardano.

This scheme requires changes to existing work on BIP-0039 mnemonics and SLIP-0023 Cardano universal master node derivation.

No changes will be necessary to existing work on child key derivation.

## Acceptance Criteria

- an extended private key can be generated from a BIP-0039 mnemonic that follows the SLIP-0023 Cardano Icarus master node derivation spec
- test vectors exist for the entire HD-wallet stack and are documented

**Comment by scasplte2** [comment]
would it be possible to look into how polkadot does this as well?
