### ISSUE TITLE
As a network participant, I want to incentivise availability and tx verification so that I can be assured of uptime.

### ISSUE THREAD

**Issue by mpk2** [Topl/Bifrost#17]
Ouroboros introduces an analysis of incentives for rational groups that considers committee members and input endorsers. Saliently, it is noted that it is important to reward availability and processing (no longer need to reward hashing because that was just a clever way to randomise leader election).

**Comment by scasplte2** [comment]
Endorsers and committee members are no longer a thing in praos and genesis, so this is broadly not needed. Mechanisms for fees and reliability are still an issue that will need to be addressed.
