### ISSUE TITLE
[3pt] As a developer, I need to see only relevant, active branches

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#173]
The current branches are out of sorts, and need to be dealt with. Any branches not currently pulled into dev or an active branch need to be pruned.

**Comment by scasplte2** [comment]
Once we upgrade Topl from Monon to Dion, is it possible to archive Matt's branches and the topl_monon one somehow? Like ZIP them and store the in DB. Would that retain their committ history if we needed to import them later for some reason?

**Comment by scasplte2** [comment]
Made backups of Matt's branches and going to keep Monon open for now but will push the Dion release shortly.
