### ISSUE TITLE
[1pt] Developers want 1.0 on testnets

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#174]
- [x] Update home directory for all settings files to point to ~/ across all architectures

- [x] Configure Hel settings file for folders and keys
- [x] Set up newest release on Hel

- [x] Configure Valhalla settings file for folders and keys
- [x] Set up newest release on Valhalla

**Comment by scasplte2** [comment]
successfully deployed 1.0 to all testnets. Working on the release notes now
