### ISSUE TITLE
Developers and users need Valkyrie instrument documentation

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#175]
Provide documentation on setting up a node from source code for testing/ running, with the new requirement of placing the Valkyrie instrument JAR into the jvm/graal/jre/lib/boot classpath

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-867) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
We already have documentation in wiki
