### ISSUE TITLE
[User story] As a network user, I wish to call a chain program that issues a new smart asset. 

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#183]
## Summary
Users should be able to create new smart assets on chain.

## Questions
1. Do we build in a Valkyrie function that people can include in their programs? Make this a library code box?
1. We have a common chain program archetype that is a smart asset. People are going to want factories. Can we do that?

## Checklist

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-869) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
