### ISSUE TITLE
ProgramMethodExecution tx generator

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#185]
* [ ] Create a script to generate any number of PME tx RPC calls at once and send them to the chain
* [ ] Record the output of those tx's, including failures
* [ ] Figure out how to measure the health of the chain when sending the requests
* [ ] Build local docker image incorporating Newman
* [ ] Show that running CCI locally using my version of Newman can execute a "Get Chain Info" api call successfully
* [ ] Deploy Docker image to a place accessible by the CCI service
* [ ] Demonstrate complete process of pushing an update to Github, triggering CCI to pull the code and both docker images to run unit-tests and the end-to-end tests.
* [ ] Write the PME generation script using the Postman built-ins and test its execution on a manually launched chain
* [ ] Locally demo the  instantiation of a new private testnet that incorporates the PME gen script as part of it's CI tests
* [ ] Push everything to remote services and test that everything works as intended
* [ ] Write documentation outlining the resources used to create this testing pipeline and how to modify it for future use.
* [ ] Write out any other end-to-end tests we may want to perform on the repo in it's current state.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-871) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
## Description
I want to figure out how to automate end-to-end testing into the CircleCI workflow using Postman and this particular case as my motivation. My first attempt was to use a Newman orb but this does not run locally and I do not want to have to push to CircleCI every time to test. Instead, I am going to create my own docker image with the Newman package then define the collections that need to be run in this container using the CCI yml file. 

My first steps to accomplish this is to get the local CCI instance on Bohr (my local test machine) to run through a set of API calls defined in a local json file. Next steps are to build a docker image incorporating Newman and make sure that my simple test case works. Test case is using the Chain Info method at the moment.

## Questions
 - How can I ensure that the chain is up and running when attempting to run the API route? This must be something already figured out though. Will look into.
 - Where do I publish the docker image?

## Checklist
- [ ] Build local docker image incorporating Newman
- [ ] Show that running CCI locally using my version of Newman can execute a "Get Chain Info" api call successfully
- [ ] Deploy Docker image to a place accessible by the CCI service
- [ ] Demonstrate complete process of pushing an update to Github, triggering CCI to pull the code and both docker images to run unit-tests and the end-to-end tests.
- [ ] Write the PME generation script using the Postman built-ins and test its execution on a manually launched chain
- [ ] Locally demo the  instantiation of a new private testnet that incorporates the PME gen script as part of it's CI tests
- [ ] Push everything to remote services and test that everything works as intended
- [ ] Write documentation outlining the resources used to create this testing pipeline and how to modify it for future use.
- [ ] Write out any other end-to-end tests we may want to perform on the repo in it's current state.

**Comment by scasplte2** [comment]
tested that Newman passes when the local chain is running and fails when the chain is not (as one would expect)

**Comment by scasplte2** [comment]
dammit @scasplte2 get this done

**Comment by jingsting** [comment]
No longer applicable
