### ISSUE TITLE
[3pt] Research nonce generation schemes for replay protection

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#191]
Need to devise a way for users to deploy unique PME transactions to the chain

**Comment by Tuxman** [comment]
https://www.dropbox.com/home/Tech/Shared/Literature/Replay%20Attacks

Link to research papers on replay attack classification, strategies, and prevention.

**Comment by scasplte2** [comment]
After a discussion with Alex, we recalled that the inclusion of fee boxes uniquely defines each transaction so there is no need for additional replay attack protection.
