### ISSUE TITLE
[#pt] Valkryie function to burn assets through coord program

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#206]
Create a valkyrie-only function that can directly dereference and destroy assets from the UTXO set

* [ ] Valkyrie function targeting a specific AssetBox given an asset record parameter
* [ ] JS template function to wrap an assetBurn Valkyrie function
* [ ] Test to atomically burn an asset from the protocol level and program level

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-874) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
