### ISSUE TITLE
[#pt] Integrate specification of smart asset coordination program into Bifrost

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#209]
define mandatory fields and behavior for non-fungible assets, both divisible and non-divisible.

* [ ] Document design choices and motivations for the different types of smart assets
* [ ] Create a JavaScript module template for assets, to be used to implement smart asset coordination programs

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-875) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
The first thing to do this will be a definition of the chainAssetModel that is currently being worked on

**Comment by jingsting** [comment]
No longer applicable with off chain smart asset management
