### ISSUE TITLE
[5pt] Authenticated dictionary simulation

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#217]
Implement a version of the algorithm described in "Improving Authenticated Dynamic Dictionaries, with Applications to Cryptocurrencies" from https://eprint.iacr.org/2016/994.pdf.

* [x] quick simulation in JavaScript
* [ ] Full-featured implementation in Scala

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-878) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
familiarity with the AVL+ trees as discussed in the paper but moving to the icebox for now as we may use this again in the future.

**Comment by jingsting** [comment]
Foregoing authenticated state for now
