### ISSUE TITLE
[8pt] RSA accumulators research

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#218]
https://ethresear.ch/t/accumulators-scalability-of-utxo-blockchains-and-data-availability/176/25

https://blog.goodaudience.com/deep-dive-on-rsa-accumulators-230bc84144d9

https://eprint.iacr.org/2016/994.pdf

Investigate and document the usability of RSA accumulators for updating and verifying smart asset properties.

**Comment by scasplte2** [comment]
Have the ability to generate accumulators on Scala and JS side but still need to check.

**Comment by Tuxman** [comment]
Created new repository for this project at https://github.com/Topl/rsa-accumulator
