### ISSUE TITLE
[8pt] Coordinate with Sudeesh and Alex to ensure their processes with the newest version of the main net

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#224]
All of this is documentation for future release purposes, treat each subtask as a piece of documentation to be created and added to the corpus of knowledge regarding node upgrades.

- [x] Account for all known running nodes in the mainnet
- [x] Set date and fork block height to switch over all nodes
- [x] 1. Backup chain data immediately before turning off forging bootstrap node
- [x] 2. Turn off forging bootstrap node
- [x] 3. Turn off all other nodes
- [x] 4. Restart bootstrap node, confirm forging is successful after hitting designated block height
- [x] 5. Allow other nodes to restart and reconnect

**Comment by Tuxman** [comment]
All nodes are accounted for connected to the mainnet, can proceed with testing update release rollout plan.

**Comment by scasplte2** [comment]
further documentation of this process has been taken care of in #231
