### ISSUE TITLE
[8pt] Figure out Docker hub access for adding people to organizations and allow them to push to the toplprotocol organization

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#226]
- [x] Add members to toplprotocol organization
- [x] Create initial Bifrost image & push to toplprotocol Bifrost repo
- [x] Script out a release plan that bumps version number in Docker
- [x] Create CI/CD pipeline to push new image when a new Bifrost release is created

**Comment by scasplte2** [comment]
further documentation of this process has been taken care of in #231
