### ISSUE TITLE
[#pt] Separate asset record mapping into secondary write-access StateBox

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#227]
The goal is to hold assets in a separate StateBox from the rest of program state, and only allow predefined operations from the Valkyrie functions to directly read, update, and delete asset records.

* [ ] Refactor program/ExecutionBox to incorporate a second write-access StateBox
* [ ] Open and populate a set for asset records in ephemeral state in the Valkyrie instrument
* [ ] Change Valkyrie functions to target asset records from this set and match to the corresponding AssetBox

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-879) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
