### ISSUE TITLE
[3pt] Fee management for program owners

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#228]
All current asset creating keys will now need an amount of arbits/polys to pay for PME transactions when interacting with smart asset programs.

* [ ] Develop scheme to distribute funds to involved parties
* [ ] Test and validate that each party can submit valid txs

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-880) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
