### ISSUE TITLE
[2pt] Documentation on deploying dockerized Bifrost release

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#231]
Make documentation for how to go from work in dev -> master -> release and have the docker containers made

- [ ] Map out mainnet upgrade plan
- [x] Document release upgrade CI/CD pipeline

**Comment by Tuxman** [comment]
Topl/documentation/@4b5f4f6

**Comment by Tuxman** [comment]
Topl/Documentation@2857051
