### ISSUE TITLE
Refactor Valkyrie Instrument for Graalvm 19.3.0

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#238]
Upgrading Graalvm from 19.2.0 to 19.3.0 breaks the registration of a Valkyrie Instrument. Follow the [SimpleTool](https://github.com/graalvm/simpletool) example for ideas on how to properly refactor the instrument to a cleaner, working state.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-881) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
