### ISSUE TITLE
[5pt] Allow Valhalla forgers to reboot seamlessly

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#249]
- [x] Cron job to reboot server once a day
- [x] Restart Bifrost process in a new screen instance
- [x] Unlocking forging keyfile after Bifrost has spun up

**Comment by jingsting** [comment]
Link to Daily Reboot doc
https://paper.dropbox.com/doc/Daily-Reboot--AyJT1QxZ7Ntrse7iRflsm7mrAQ-krRbQDCt8RMU2EDIoSp2U
