### ISSUE TITLE
[5pt] Create Zulip bot for alerting of node health

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#253]
- [x] research how to integrate with a bot
- [x] setup node integration with bot
- [x] monitor for stderr output from node
- [x] measure and report unusual block times
- [x] Send reboot successfully message to stream

**Comment by Tuxman** [comment]
https://paper.dropbox.com/doc/Daily-Reboot--AzX66MxrATboyJCwJ7qMpsjFAg-krRbQDCt8RMU2EDIoSp2U

**Comment by jingsting** [comment]
Looked at the changes that Nick made, we are using GMT for timezone and not using sudo for crontab
