### ISSUE TITLE
[5pt] Create network diagram documenting Bifrost networking

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#262]

**Comment by jingsting** [comment]
Link to the diagram:
https://www.figma.com/file/qcYYGFPY2vRSYbLVUDVIkQ/Network-Diagram-V1.0?node-id=2%3A2

**Comment by scasplte2** [comment]
@jingsting this is a good start for the diagram but it is a little confusing for me to try and make out on my own. Could we schedule a time (maybe Tues. 12pm - 1pm?) to go over this so I can see what your thoughts are here.

Also, really glad you chose Figma! I've recently found it and really like the app as well.

**Comment by scasplte2** [comment]
Version 1 of diagram

![Mask Group](https://user-images.githubusercontent.com/1753335/77096562-8186b780-69dd-11ea-870f-692c41e453b6.png)
