### ISSUE TITLE
Evaluate garbage collection

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#267]
In reference to issue #264 (which has been resolved), we began to investigate the root of stability issues in Bifrost and narrowed it down to garbage collections

Hypothesis - Something is causing excessive garbage collection

Experiment - Heap dumps to identify everything in the JVM heap space.

Conclusion - Analyzing the heap dumps, many "::" operations are being performed on a single object held by an Akka dispatcher thread from the NodeViewHolder. Tracing the source down to the exact operation being performed and removing it will resolve the situation.

---
Involves finding a tool to identify which classes are generating the byte arrays seen in the heap dump.

---
### Doneness
determine what it takes to evaluate an actor at the most granular level and thereby determine what a healthy state of the code execution is.

**Comment by Tuxman** [comment]
Following an article http://www.learnings.today/investigating-cpu-usage-in-a-java-process/
 and using Jstack to print out a thread dump, I isolated 4 threads from the Java process. All 4 were garbage collection threads, meaning the main performance issue is a large amount of data being garbage collected.

**Comment by scasplte2** [comment]
Previous work has identified this as a major issue to continue investigating for future stability of the node client.

**Comment by Tuxman** [comment]
I have traced the issue through this call:
`akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread`
My next step is to analyze Akka further and try to discover why this thread is generating so many objects in the heap.

**Comment by scasplte2** [comment]
Using the Grafana dashboard we have identified a number of metrics to consider that impact the performance of actors. Notably, considering the time spent performing spans (using Zipkin), the time spent processing messages (Grafana), and the CPU usage for garbage collection (visual VM)
