### ISSUE TITLE
[1pt] Evaluate the effectiveness of implementing cache system for LSMStore

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#275]
Have a discussion with Aaron about whether it would be feasible and useful to migrate his cache feature into Bifrost

**Comment by Tuxman** [comment]
I talked with Aaron about adding in a cache using Guava. It is very easy to implement and involves adding a few lines of code. A working implementation can be found in Prosomo at The implementation in Prosomo is under /src/main/scala/prosomo/history/BlockStorage.scala/ lines 23-43.
