### ISSUE TITLE
BN-951 ⁃ [User Story] - repo activity

### ISSUE THREAD

**Issue by ghost** [Topl/Bifrost#2882]
### Summary

*As a contributor, I want to be able to get feedback quickly, so I can contribute more.*

### Notes

Affects mainly: Issue and PR processing.

Max. Response time needs to be some hours (12?)

---

https://topl.atlassian.net/browse/BN-951

**Comment by abebeos** [comment]
@scasplte2 you cannot decentralize a project if there is a "barrier to contribution" in the form of low activity.

It is practically impossible to contribute, if there are always days of delays. A contributor depends here on the (centralized) authorities (those who decide and push the buttons on the repo).

So, in essence, you need to ensure that thigs go much much faster here.
