### ISSUE TITLE
[3pt] Implement cache system for key-value store

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#291]
Following Aaron's example in Prosomo, implement the cache system in front of LSMStore.

Should replace the disk lookup of the last 50-100 blocks. Expected to speed up the evaluation of best block and height of chain.

**Comment by Tuxman** [comment]
The implementation in Prosomo is under /src/main/scala/prosomo/history/BlockStorage.scala/ lines 23-43.
