### ISSUE TITLE
[3pt] Compare stability-fix branch performance to dev

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#328]

**Comment by scasplte2** [comment]
Ran simulations on Michselon with the stability fix and dev branches

### Overview actor stats
![image](https://user-images.githubusercontent.com/1753335/82246047-a037fa80-9909-11ea-8483-31c8e7bcadbb.png)

### Comparison of time spent
![image](https://user-images.githubusercontent.com/1753335/82245938-77b00080-9909-11ea-9b47-c8c44450b448.png)

### Comparison of JVM memory pools
![image](https://user-images.githubusercontent.com/1753335/82246154-c8bff480-9909-11ea-98b4-3810739de5b7.png)

Overall nothing seems overly concerning between the two runs so going to close this issue.
