### ISSUE TITLE
[8pt] Remove all unneeded/leftover Scorex classes and functions

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#331]
There are many classes and functions littered through Bifrost that no longer serve a purpose and should be cleaned out to increase readability and robustness of the codebase.

Reviewer:
@Tuxman @jingsting @scasplte2 

| File                                                            | Change | Complete |
|-----------------------------------------------------------------|--------|----------|
| api                                                             | modified       | &check;        |
| api/http                                                        | modified       | &check;         |
| api/http/ApiError.scala                                         | deleted       | &check;         |
| api/http/ApiResponse.scala                                      | modified       | &check;         |
| api/http/ApiRoute.scala                                         | modified       | &check;         |
| api/http/ApiRouteWithView.scala                                 | none       | &check;         |
| api/http/AssetApiRoute.scala                                    | modified       | &check;         |
| api/http/CompositeHttpService.scala                             | none       | &check;         |
| api/http/CorsSupport.scala                                      | none        | &check;         |
| api/http/DebugApiRoute.scala                                    | modified       | &check;         |
| api/http/NodeViewApiRoute.scala                                 | modified       | &check;         |
| api/http/PeersApiRoute.scala                                    | none       | &check;         |
| api/http/ProgramApiRoute.scala                                  | modified       | &check;         |
| api/http/ScorexApiResponse.scala                                | deleted       | &check;         |
| api/http/SuccessApiResponse.scala                               | deleted       | &check;         |
| api/http/UtilsApiRoute.scala                                    | modified       | &check;         |
| api/http/WalletApiRoute.scala                                   | modified       | &check;         |
| app                                                             | modified       | &check;         |
| app/ApplicationVersion.scala                                    | modified       | &check;         |
| BifrostApp.scala                                                | none       | &check;         |
| BifrostLocalInterface.scala                                     | modified       | &check;         |
| BifrostNodeViewHolder.scala                                     | modified       | &check;         |
| BifrostSyncInfoMessageSpec$.scala                               | modified       | &check;         |
| block                                                           | modified       | &check;         |
| block/Block.scala                                               | deleted    |     &check;     |
| block/BlockValidator.scala                                      | none    |    &check;      |
| blocks                                                          | deleted      |       &check;   |
| blocks/BifrostBlock.scala                                       | modified       |    &check;      |
| blocks/Bloom.scala                                              | modified     |     &check;     |
| consensus                                                       | modified       | &check;         |
| consensus/BlockChain.scala                                      | deleted       | &check;         |
| consensus/ConsensusSettings.scala                               | modified       | &check;         |
| consensus/History.scala                                         | modified       | &check;         |
| consensus/SyncInfo.scala                                        | modified       | &check;         |
| crypto                                                          | modified       | &check;         |
| crypto/Bip39.scala                                              | none       | &check;         |
| crypto/hash                                                     | deleted       | &check;         |
| crypto/hash/FastCryptographicHash.scala                         | modified       | &check;         |
| .DS_Store                                                       | deleted       | &check;         |
| exceptions                                                      | modified       | &check;         |
| exceptions/InvalidProvidedContractArgumentsException.scala      | modified       | &check;         |
| exceptions/JsonParsingException.scala                           | none       | &check;         |
| exceptions/TransactionValidationException.scala                 | none       | &check;         |
| forging                                                         | modified       | &check;         |
| forging/Forger.scala                                            | modified       | &check;         |
| forging/ForgingConstants.scala                                  | deleted       | &check;         |
| forging/ForgingSettings.scala                                   | modified       | &check;         |
| history                                                         | none       | &check;         |
| history/BifrostHistory.scala                                    | none       | &check;         |
| history/BifrostStorage.scala                                    | none       | &check;         |
| history/BifrostSyncInfo.scala                                   | modified       | &check;         |
| inflation                                                       | deleted       | &check;         |
| inflation/InflationQuery.scala                                  | deleted       | &check;         |
| keygen                                                          | deleted       | &check;         |
| keygen/KeyFile.scala                                            | modified       | &check;         |
| mempool                                                         | modified       | &check;         |
| mempool/BifrostMemPool.scala                                    | modified       | &check;         |
| network                                                         |    none    |     &check;     |
| network/BifrostNodeViewSynchronizer.scala                       |    none    |    &check;      |
| network/Buffering.scala                                         |   none     |     &check;     |
| network/Handshake.scala                                         |     none   |   &check;       |
| network/message                                                 |     none   |    &check;      |
| network/message/BasicMessagesRepo.scala                         |   none     |   &check;       |
| network/message/MessageHandler.scala                            |    none    |   &check;       |
| network/message/Message.scala                                   |    none    |  &check;        |
| network/message/MessageSpec.scala                               |   none     |    &check;      |
| network/NetworkController.scala                                 |    none    |     &check;     |
| network/peer                                                    |   none     |     &check;     |
| network/PeerConnectionHandler.scala                             |  none      |   &check;       |
| network/peer/PeerDatabaseImpl.scala                             |   modified     |     &check;     |
| network/peer/PeerDatabase.scala                                 |   deleted  |   &check;       |
| network/peer/PeerManager.scala                                  |    modified    |   &check;       |
| network/PeerSynchronizer.scala                                  |   none     |    &check;      |
| network/ScoreObserver.scala                                     |   deleted     |    &check;      |
| network/SendingStrategy.scala                                   |    none    |    &check;      |
| network/UPnP.scala                                              |    none    |   &check;       |
| program                                                         | modified       | &check;         |
| program/AgreementTerms.scala                                    | modified       | &check;         |
| programBoxRegistry                                              | deleted       | &check;         |
| programBoxRegistry/PBRStorage.scala                             | deleted       | &check;         |
| programBoxRegistry/ProgramBoxRegistryOld.scala                  | deleted       | &check;         |
| programBoxRegistry/ProgramBoxRegistry.scala                     | modified       | &check;         |
| program/ExecutionBuilder.scala                                  | modified       | &check;         |
| program/FulfilmentFunction.scala                                | deleted       | &check;         |
| program/ProgramPreprocessor.scala                               | none       | &check;         |
| program/Program.scala                                           | none       | &check;         |
| program/ShareFunction.scala                                     | deleted       | &check;         |
| program/ValkyrieFunctions.scala                                 | deleted       | &check;         |
| scorexMod                                                       | modified       | &check;         |
| scorexMod/GenericApplication.scala                              | none       | &check;         |
| scorexMod/GenericBoxMinimalState.scala                          | none       | &check;         |
| scorexMod/GenericBox.scala                                      | modified       | &check;         |
| scorexMod/GenericBoxTransaction.scala                           | modified       | &check;         |
| scorexMod/GenericMinimalState.scala                             | none       | &check;         |
| scorexMod/GenericNodeViewHolder.scala                           | none       | &check;         |
| scorexMod/GenericNodeViewSynchronizer.scala                     | none       | &check;         |
| scorexMod/GenericStateChanges.scala                             | none       | &check;         |
| scorexMod/GenericWalletBox.scala                                | none       | &check;         |
| scorexMod/LocalInterface.scala                                  | none       | &check;         |
| scorexMod/NodeViewComponent.scala                               | none       | &check;          |
| scorexMod/NodeViewModifier.scala                                | none       | &check;         |
| serialization                                                   | none       | &check;         |
| serialization/BytesSerializable.scala                           | none       | &check;         |
| serialization/JsonSerializable.scala                            | none       | &check;         |
| serialization/Serializer.scala                                  | none       | &check;         |
| settings                                                        | none       | &check;         |
| settings/Settings.scala                                         | none       | &check;         |
| state                                                           | modified       | &check;         |
| state/BifrostState.scala                                        | none       | &check;         |
| tokenBoxRegistry                                                | deleted       | &check;         |
| tokenBoxRegistry/TokenBoxRegistry.scala                         | modified       | &check;         |
| transaction                                                     | modified       | &check;         |
| transaction/account                                             | deleted       | &check;         |
| transaction/account/AccountTransactionsHistory.scala            | deleted       | &check;         |
| transaction/account/BalanceSheet.scala                          | deleted       | &check;         |
| transaction/account/PublicKeyNoncedBox.scala                    | modified       | &check;         |
| transaction/bifrostTransaction                                  | modified       | &check;         |
| transaction/bifrostTransaction/ArbitTransfer.scala              | none       | &check;         |
| transaction/bifrostTransaction/AssetCreation.scala              | none       | &check;         |
| transaction/bifrostTransaction/AssetRedemption.scala            | none       | &check;         |
| transaction/bifrostTransaction/AssetTransfer.scala              | none       | &check;         |
| transaction/bifrostTransaction/BifrostTransaction.scala         | none       | &check;         |
| transaction/bifrostTransaction/CodeCreation.scala               | none       | &check;         |
| transaction/bifrostTransaction/CoinbaseTransaction.scala        | none       | &check;         |
| transaction/bifrostTransaction/PolyTransfer.scala               | none       | &check;         |
| transaction/bifrostTransaction/ProgramCreation.scala            | none       | &check;         |
| transaction/bifrostTransaction/ProgramMethodExecution.scala     | none       | &check;         |
| transaction/bifrostTransaction/ProgramTransaction.scala         | none       | &check;         |
| transaction/bifrostTransaction/ProgramTransfer.scala            | none       | &check;         |
| transaction/bifrostTransaction/TransferTransaction.scala        | none       | &check;         |
| transaction/bifrostTransaction/TransferUtil.scala               | none       | &check;         |
| transaction/box                                                 | modified       | &check;         |
| transaction/box/BifrostBox.scala                                | none       | &check;         |
| transaction/box/BifrostNoncedBox.scala                          | modified       | &check;         |
| transaction/box/BifrostProgramBox.scala                         | none       | &check;         |
| transaction/box/Box.scala                                       | none       | &check;         |
| transaction/box/BoxUnlocker.scala                               | none       | &check;         |
| transaction/box/proposition                                     | modified       | &check;         |
| transaction/box/proposition/MofNProposition.scala               | none       | &check;         |
| transaction/box/proposition/Proposition.scala                   | none       | &check;         |
| transaction/box/proposition/PublicKey25519Proposition.scala     | none       | &check;         |
| transaction/box/PublicKey25519NoncedBox.scala                   | deleted       | &check;         |
| transaction/BoxTransaction.scala                                | deleted       | &check;         |
| transaction/MemoryPool.scala                                    | modified       | &check;         |
| transaction/proof                                               | deleted       | &check;         |
| transaction/proof/MultiSignature25519.scala                     | modified       | &check;         |
| transaction/proof/Proof.scala                                   | modified       | &check;         |
| transaction/proof/Signature25519.scala                          | modified       | &check;         |
| transaction/serialization                                       | none       | &check;         |
| transaction/serialization/AgreementCompanion.scala              | none       | &check;         |
| transaction/serialization/ArbitTransferCompanion.scala          | none       | &check;         |
| transaction/serialization/AssetCreationCompanion.scala          | none       | &check;         |
| transaction/serialization/AssetRedemptionCompanion.scala        | none       | &check;         |
| transaction/serialization/AssetTransferCompanion.scala          | none       | &check;         |
| transaction/serialization/BifrostTransactionCompanion.scala     | none       | &check;         |
| transaction/serialization/CodeBoxCreationCompanion.scala        | none       | &check;         |
| transaction/serialization/CoinbaseTransactionCompanion.scala    | none       | &check;         |
| transaction/serialization/PolyTransferCompanion.scala           | none       | &check;         |
| transaction/serialization/ProgramCreationCompanion.scala        | none       | &check;         |
| transaction/serialization/ProgramMethodExecutionCompanion.scala | modified       | &check;         |
| transaction/serialization/ProgramTransactionCompanion.scala     | modified       | &check;         |
| transaction/serialization/ProgramTransferCompanion.scala        | none       | &check;         |
| transaction/serialization/TransferSerializer.scala              | none       | &check;         |
| transaction/serialization/TransferTransactionCompanion.scala    | deleted       | &check;         |
| transaction/SimplePaymentGenerator.scala                        | deleted       | &check;         |
| transaction/state                                               | deleted       | &check;         |
| transaction/state/authenticated                                 | deleted       | &check;         |
| transaction/state/authenticated/BoxMinimalState.scala           | deleted       | &check;         |
| transaction/state/MinimalState.scala                            | deleted       | &check;         |
| transaction/state/SecretHolder.scala                            | modified       | &check;         |
| transaction/state/StateChanges.scala                            | deleted       | &check;         |
| transaction/Transaction.scala                                   | modified       | &check;         |
| transaction/wallet                                              | deleted       | &check;         |
| transaction/wallet/Vault.scala                                  | modified       | &check;         |
| utils                                                           | modified       | &check;         |
| utils/BlockTypeable.scala                                       |    deleted    |    &check;      |
| utils/NetworkTime.scala                                         | deleted       | &check;         |
| utils/ScorexLogging.scala                                       | modified       | &check;         |
| utils/SerializationConstants.scala                              | deleted       | &check;         |
| utils/utils.scala                                               | deleted       | &check;         |
| validation                                                      | deleted       | &check;         |
| validation/DifficultyBlockValidator.scala                       | modified       | &check;         |
| wallet                                                          | modified       | &check;          |
| wallet/BWallet.scala                                            | modified       | &check;          |
| wallet/PolyTransferGenerator.scala                              | deleted       | &check;          |

**Comment by Tuxman** [comment]
I removed the ApiClient file entirely

**Comment by scasplte2** [comment]
@Tuxman did you archive this file? I think I'd like to use it eventually for demo purposes. Maybe just saving it in the Dropbox is good though

**Comment by Tuxman** [comment]
The ApiClient file? No, I'll put it in Dropbox as a reference file though.

**Comment by Tuxman** [comment]
I am modifying the entire api directory
