### ISSUE TITLE
[3pt] Documentation for the monitoring tools

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#333]
- [x] plots of behavior
- [x] quick start guide
- [x] installation instructions
- [x] description of how the tools interact and behave

**Comment by jingsting** [comment]
Link to Bifrost environment setup script
https://paper.dropbox.com/doc/Bifrost-Install-Graalvm--AyI4FADOgdFSpsxcPwPqa5NDAQ-HXWtzZDU4pzXkpqECYZml

**Comment by jingsting** [comment]
@scasplte2

**Comment by scasplte2** [comment]
@jingsting @Tuxman 
Please make a section in the Bifrost wiki for monitoring tools with the following sections
## Kamon monitoring tools -> put the paper write up here
### Example: Zipkin -> put plots from Zipkin
### Example: Grafana -> plots from Grafana

**Comment by scasplte2** [comment]
https://github.com/Topl/Bifrost/wiki

Bifrost wiki is updated. Didn't tag my commits 😿 Here is proof though
![image](https://user-images.githubusercontent.com/1753335/83207429-cd11bc00-a118-11ea-8e1f-30678baf3733.png)

**Comment by scasplte2** [comment]
Please take a look @jingsting @Tuxman and close if y'all are happy with the wiki for now

**Comment by Tuxman** [comment]
Looks good :+1:
