### ISSUE TITLE
[2pt] Compare the performance of LSMStore and Guava Cache in BifrostStorage

### ISSUE THREAD

**Issue by jingsting** [Topl/Bifrost#334]

**Comment by jingsting** [comment]
Below are some times taken for cache and storage to access the latest 500 blocks:
-Cache--------Storage-
5.302ms   <   5.318ms
5.812ms   <   6.843ms
5.085ms   >   5.078ms
5.635ms   <   5.638ms

**Comment by jingsting** [comment]
Unit: Milliseconds
| Last 500 Blocks [Cache] | Less Than | Last 500 Blocks [LSMstore] | Accessing Same Block 500 Times [Cache] | Less Than | Accessing Same Block 500 Times [LSMstore] 
|---|---|---|---|---|---|
| 4897 | true | 5016 | 0 | true | 1 |
| 4931 | false | 4876 | 0 | false | 0 |
| 4902 | true | 4971 | 0 | = | 0 |
| 4860 | true | 4866 | 0 | = | 0 |
| 4881 | false | 4881 | 0 | = | 0 |
| 4893 | false | 4887 | 0 | = | 0 |
| 4871 | true | 4895 | 0 | = | 0 |
| 4896 | false | 4849 | 0 | = | 0 |
| 4909 | true | 5373 | 0 | = | 0 |
| 4842 | false | 4842 | 1 | false | 0 |
| 4857 | true | 4862 | 0 | = | 0 |
| 4846 | false | 4846 | 0 | = | 0 |
| 4860 | false | 4819 | 0 | = | 0 |
| 4853 | true | 4867 | 0 | = | 0 |
| 4821 | true | 4832 | 0 | = | 0 |
| 4899 | false | 4851 | 0 | = | 0 |
| 4868 | true | 4889 | 0 | = | 0 |
| 4856 | true | 4895 | 0 | = | 0 |
| 4885 | true | 5573 | 0 | = | 0 |
| 4870 | true | 4879 | 0 | true | 1 |
| 4862 | true | 4877 | 1 | false | 0 |
| 4851 | true | 4858 | 0 | = | 0 |
| 4865 | true | 5226 | 0 | = | 0 |
| 4858 | true | 4865 | 0 | = | 0 |
| 4855 | true | 4883 | 0 | = | 0 |
| 4859 | false | 4844 | 1 | false | 0 |
| 4828 | true | 4856 | 0 | = | 0 |
| 4859 | false | 4826 | 0 | = | 0 |
| 4829 | true | 4846 | 0 | = | 0 |
| 4841 | true | 4872 | 0 | = | 0 |
| 4840 | false | 4817 | 0 | = | 0 |
| 5583 | false | 4872 | 1 | false | 0 |
| 4841 | true | 4911 | 0 | = | 0 |
| 4838 | false | 4833 | 0 | = | 0 |
| 4867 | false | 4820 | 0 | = | 0 |
| 4845 | true | 4869 | 0 | = | 0 |
| 4832 | false | 4805 | 0 | = | 0 |
| 4834 | true | 4839 | 0 | = | 0 |
| 4840 | true | 4860 | 0 | = | 0 |
| 4864 | false | 4846 | 0 | = | 0 |
| 4854 | false | 4833 | 1 | false | 0 |
| 4837 | true | 4866 | 0 | = | 0 |
| 4854 | false | 4840 | 0 | = | 0 |
| 4821 | true | 4861 | 1 | false | 0 |
| 4854 | false | 4848 | 0 | = | 0 |
| 4799 | true | 4825 | 0 | = | 0 |
| 4822 | true | 4852 | 0 | = | 0 |
| 5951 | false | 4922 | 0 | = | 0 |
| 4813 | false | 4811 | 0 | = | 0 |
| 4810 | true | 4842 | 0 | = | 0 |

**Comment by scasplte2** [comment]
Avg +/- Std. Dev

Cache: 4892.06 +/- 186 ms
LSMStore: 4893.88 +/- 136 ms
