### ISSUE TITLE
[2pt] Change chain backup to DO space

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#343]
Redirect the weekly snapshot of toplnet data to be stored in the Digital Ocean space

**Comment by Tuxman** [comment]
Using the [sync-uploader](https://github.com/Topl/scripts/blob/master/sh/sync-uploader) script, a cron job runs at midnight UTC to tar the backup blockchain data and store the tarball in a folder under the Digital Ocean space.

**Comment by Tuxman** [comment]
The shared folder in Dropbox has also been deleted.

**Comment by jingsting** [comment]
Just walked through the scripts with Nick
