### ISSUE TITLE
Investigate syncing issues on Valhalla query nodes

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#358]
The two query nodes for Valhalla Torus are consistently getting out of sync. One will lag behind by 3+ blocks. API requests to Valhalla Torus will be sent round-robin style, meaning approximately half the requests will be sent to an out of sync node. The aim of this initiative is to find the errors causing the nodes to get out of sync, and show that the query nodes can stay synced for a period of time after fixing the errors.

**Comment by Tuxman** [comment]
The query nodes were trying to forge, and getting bad hit values because they do not have complete wallet data to forge properly.
