### ISSUE TITLE
[2pt] Use JMH to compare performance of LSMstore and cache

### ISSUE THREAD

**Issue by jingsting** [Topl/Bifrost#361]

**Comment by jingsting** [comment]
- cacheTest / storageTest:  time taken to access the entries with block IDs for the last 500 blocks, using the parent ID from parsed data in each block

- cacheRead / storageRead: time taken to access the entries with block IDs for the last 500 blocks, using the block IDs previously stored in a variable

Here below is the result for running 10 iterations:

|Benchmark         |        Mode    |     Cnt     |      Score      |     Error  Units|
|---|---|---|---|---|
|DBOperations.cacheTest  |  avgt |  10 | 3941213921.800  | ± 225084392.017  ns/op
| DBOperations.storageTest |  avgt  | 10 |  3772633906.433  |±  85647734.637  ns/op
|DBOperations.cacheRead |   avgt  | 10   |    72299.003 | ±    312.540  ns/op
|DBOperations.storageRead |  avgt   | 10   |   133691.565  |±       818.064  ns/op

[success] Total time: 976 s (16:16), completed Apr 23, 2020 11:19:25 PM

**Comment by scasplte2** [comment]
@jingsting for future results, please quote numbers in reasonable units.

|         Benchmark        | Mode | Cnt |        Score       |       Error Units       |
|:------------------------:|:----:|:---:|:------------------:|:-----------------------:|
| DBOperations.cacheTest   | avgt | 10  | 3.941213921800 sec | ± 225.084392017 msec/op |
| DBOperations.storageTest | avgt | 10  | 3.772633906433 sec | ± 85.647734.637 msec/op |
| DBOperations.cacheRead   | avgt | 10  | 72.299003 usec     | ± .312540 usec/op       |
| DBOperations.storageRead | avgt | 10  | 133.691565 usec    | ± .818064 usec/op       |

**Comment by Tuxman** [comment]
Results and interpretation has been added to a separate document also.
