### ISSUE TITLE
[3pt] Document program control flow until crash

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#369]
Extending from #267, use a specified database state to reproduce a runaway garbage collection issue that results in an out of memory error.
- [x] reproduce the state
- [x] Identify which components are being activated up to the crash
- [x] Identify possible sources of the memory leak

**Comment by jingsting** [comment]
Possibly corrupt data was found in the best block in garbage collection issue data, the number of transaction expected (numTxExpected) parsed was negative, causing Bifrost to go into an infinite loop trying to parse the best block.

Below are some output collected when printing out the variables in the function: parseBytes2xAndBefore or parseBytes (for getting the best block)

[gc-issue-parentBlock.txt](https://github.com/Topl/Bifrost/files/4576521/gc-issue-parentBlock.txt)
[toplnet-bestBlock.txt](https://github.com/Topl/Bifrost/files/4576522/toplnet-bestBlock.txt)
[gc-issue-bestBlock.txt](https://github.com/Topl/Bifrost/files/4576523/gc-issue-bestBlock.txt)

**Comment by jingsting** [comment]
@Tuxman @scasplte2
