### ISSUE TITLE
[1pt] Space out the time nodes restart daily

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#374]

**Comment by scasplte2** [comment]
Please let me know what the schedule ends up being so that i can put it on the maintenance calendar

**Comment by Tuxman** [comment]
@scasplte2 The times for each node in the Valhalla network are as follows:

1. Valhalla-s0: 17:00:00 UTC (12:00:00 CDT)
2. Valhalla-q1: 19:00:00 UTC (14:00:00 CDT)
3. Valhalla-s1: 21:00:00 UTC (16:00:00 CDT)
4. Valhalla-q2: 23:00:00 UTC (18:00:00 CDT)

**Comment by scasplte2** [comment]
Nodes have been restarting at 2 hour intervals
