### ISSUE TITLE
Freya v0.5

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#39]
Extend the Contract Viewer to include:
- Basic Functionality
- Contract Negotiation & Deployment
- Divine Interactions

See Freya spec for details.

**Comment by balinskia** [comment]
TODO:
- change routing, so the logo and menu don't change when switching routes
- create route for: create contract and contract viewer
- in create contract route add list of contracts which are fetched from electrons local storage
- in create contract route add new form for adding new contract

**Comment by scasplte2** [comment]
this needs to be moved to a different repo
