### ISSUE TITLE
[Gjal] identify components and outline responsibilities

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#443]

**Comment by scasplte2** [comment]
Gjalarhorn components
 - keymanager
  - should create keys
  - should import a single from disk
  - should export a single to disk
  - use BIP-39 mnemoics
- requests
  - should be able to query a chainProvider for any remote request (chainProvider is defaulted to localhost on 9085)
- parent (brambl)
  - coordinate between keymanger and the request module
- Wallet scanner
  - this should query a CP for helping rebuilding a UTXO set in the wallet
- Local wallet service
  - HTTP interface for receiving requests sent to a local Bifrost instance

**Comment by ngjulia** [comment]
1. Building out key manager part → replicate that from BramblJS
        keep mneumonics
2. Figuring out how to handle local only requests where the keymanager is handling request, assuming you have a key, is handled by wallet
        HTTP transport
3. Migrating from HTTP transport to some internal mechanism like IPC
4. Implementing bloom filters, scanning mechanism for tabulating balances→ build up wallet file
