### ISSUE TITLE
Contract Signing Tab

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#46]
A separate section to sign a contract that has already been finalized.
- The public key used to sign the contract
- The contract agreement

Repopulate the text editor with the signed contract.

**Comment by scasplte2** [comment]
Where does this stand?

**Comment by AHBruns** [comment]
Will determine this tomorrow, 24/7/18, after the team talk surrounding Freya.

**Comment by AHBruns** [comment]
Sounds like we will be shifting to core functionality. Going to move this to backlog. Also, updating time req since it's optimistic, to say the least.

**Comment by scasplte2** [comment]
should actually be something in Freya
