### ISSUE TITLE
Determine utility of scorex logging to file

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#463]
Figure out how we want to do logging. Is it common to take the stdout to a log file and then rotate that or should we restrict the stdout info and print more info to log files? If we do the latter , how do we ensure log rotation?

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-887) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
We decided against logging to file at the application level
