### ISSUE TITLE
Specify types of boxes to bring into Valkryie instrument

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#468]
2019.11.25 - make token box transfers into the valkyrie instrument more efficient by including a flag of what types of boxes to send in. This should be possible given that assetTransfer, polyTransfer, and arbitTransfer are separate transactions. Currently, all boxes from a user are sent into the valk instr. (I think)

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-892) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
