### ISSUE TITLE
Separate execBuilder and preogramPreprocessor

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#470]
2019.11.26 - refactor the relationship between the executionBuilder and the programPreprocessor. Currently the executionBuilder just gives some metadata to the PPP and this functionality could be rolled into the PPP.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-894) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
