### ISSUE TITLE
Create UML-style diagrams

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#483]
outline the methods and properties of the constituent pieces of Gjallarhorn. First focus should be on the capabilities available in BramblJS (Requests Key manager, and application)

**Comment by ngjulia** [comment]
https://docs.google.com/document/d/1PW8nwzjds013GKOTXvpGqSS6Xkvl2kbjFTjSr5jmfqc/edit

**Comment by fmendoz7** [comment]
https://www.figma.com/file/yaJsP8orNj3ylcHvdosLT4/UML-Diagram?node-id=0%3A1

**Comment by scasplte2** [comment]
@ngjulia @fmendoz7 
I'm a little confused by what the diagram is trying to convey. Overall I like that you guys included all the methods and properties but on the top you reference Brambl and then only describe the requests module (sort of). Having the distinction of local and remote requests is good but that is not the structure of Brambl. Did you get that list from looking at the API surface that is currently present in Bifrost? If so, that is good as a place to start and then the enumeration of the Keyfile pieces makes sense.

I'd suggest making a similar diagram for BramblJS as it might help illuminate how the whole application will need to be structured. Currently it seems that we've enumerated the sub pieces that needed to be integrated into Gjallarhorn from Bifrost, but it isn't clear to me how it will all fit together. Which is really the point of this endeavor.

**Comment by scasplte2** [comment]
@ngjulia @fmendoz7 
This is more what I have in mind. This is BramblJS
![image.png](https://images.zenhubusercontent.com/5b1444ebb709d02140684bb7/ba6e2e34-4a0e-451a-967e-4e48760a879b)

I made this in Draw io so I can provide an editable SVG or share this file if y'all want to edit it. What I mean by all fitting together is that since Brambl is the parent class that presents the API for using the BramblJS library, I can create a sequence diagram of how the Brambl.transaction function works referencing how each of the sub-modules (KeyManager and Requests, of which instances of the classes are saved in keyManager and requests respectively) interact and pass data back and forth using the Brambl parent class to coordinate between them.
