### ISSUE TITLE
Tests for multiple nodes

### ISSUE THREAD

**Issue by zihehuang** [Topl/Bifrost#5]
Blockchain level tests are lacking. In particular, these conditions need to be tested in a more rigorous manner: 

~~1. Forger needs to stop when stopForging is set to true.~~
2. `SyncInfo` needs to return a list of modifierIds.
3. Chain needs to handle rollback properly when a peer presents a higher scoring block even when the bestBlock locally is not the higher scoring block's parent.
4. Transactions generated from other nodes need to be received properly.
5. AssetRedemption's calculated BoxId is different from ContractCompletion's AssetBox

**Comment by scasplte2** [comment]
Added to Node view as these are tests to guaranteed the consistency of state, which is managed by the node view holder.
