### ISSUE TITLE
Run VisualVM during tests with and without BigInt

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#519]

**Comment by jingsting** [comment]
Looks like using BigInt didn't utilize more memory
Environment: Running `sbt test` on a mac

Before BigInt:
<img width="692" alt="88705f90" src="https://user-images.githubusercontent.com/7685067/89233721-cdfb1a00-d5af-11ea-8a00-cd744339edc6.png">

After BigInt:
<img width="698" alt="cur" src="https://user-images.githubusercontent.com/7685067/89233724-ce93b080-d5af-11ea-88a6-dc7178bd64d5.png">

**Comment by scasplte2** [comment]
@Tuxman please give this a try when you get a chance

**Comment by Tuxman** [comment]
I ran it and reproduced the error, it is the same garbage collection issue when running BifrostHistorySpec. I am going to create a new issue to cover fixing the problem.

**Comment by scasplte2** [comment]
Please add a view of VisualVM running the tests prior to the BigInt setup

**Comment by Tuxman** [comment]
I ran commit 60a7c9e0305b24c65e6526018dc01853c918f76f and finally got it to work after clearing out everything short of removing the Bifrost directory and re-cloning the repo.

![image](https://user-images.githubusercontent.com/846699/91358377-5720fd80-e7b8-11ea-88a2-19ae865cd188.png)
