### ISSUE TITLE
Diagram for Serializers

### ISSUE THREAD

**Issue by jingsting** [Topl/Bifrost#556]

**Comment by scasplte2** [comment]
please place a diagram (or text file or whatever) into Topl/documentation/engineering-diagrams

**Comment by jingsting** [comment]
![Serialization.svg](https://images.zenhubusercontent.com/5f05dbebe4c1e3085069de08/c42706ad-e15e-42ff-bab8-1b289da953ee)

**Comment by jingsting** [comment]
Attached is the revised diagram![Serialization.svg](https://images.zenhubusercontent.com/5f05dbebe4c1e3085069de08/aebbb860-ec93-4f78-9cd0-cd85296ee720)

**Comment by jingsting** [comment]
Version 3 of the diagram:
![Serialization.svg](https://images.zenhubusercontent.com/5f05dbebe4c1e3085069de08/f4bebcfb-8b2c-42f2-9726-9a979adc8954)
