### ISSUE TITLE
Standardize CodeCreation

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#562]
CodeCreation transaction is a standalone transaction, and can be standardized as a ProgramTransaction.

* [ ] Change a single key & signature to require a single entry in a Seq
* [ ] Add empty owner field

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-898) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
No longer applicable
