### ISSUE TITLE
Add standard API exceptions

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#622]
We should return useful and standard error messages. We should look into Scorex's exception handling scheme because it seems to be fairly robust (at least at a casual glance)

For example, we should explain to users required arguments when parameters are missing

┆Issue is synchronized with this [Jira Epic](https://topl.atlassian.net/browse/CORE-905) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
Already done
