### ISSUE TITLE
Asset creation for sidechain

### ISSUE THREAD

**Issue by yamir1995** [Topl/Bifrost#64]
Write new asset creation transaction type in BifrostTransaction that allows for the creation of assets after approval of deposit from sidechain

**Comment by scasplte2** [comment]
Please provide a time estimate for this at some point

**Comment by yamir1995** [comment]
Aiming to get this done by Friday

**Comment by yamir1995** [comment]
Asset creation has been completed with api endpoint. Now the manager needs to be integrated so it can make the necessary api request to trigger a transaction.

**Comment by yamir1995** [comment]
Need to add some state tests for this. Will do in the next day or two.
