### ISSUE TITLE
Setup an update method using transaction witnesses

### ISSUE THREAD

**Issue by scasplte2** [Topl/Bifrost#694]
The WCH should use its wallet info to decide if its companion wallet cares about updates in the latest block. If it does then a transaction witness is computed and the transaction sent to the gjal instance to update its internal state.

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-914) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
This is not relevant at the moment as the WCH is completely trusted and block headers are not communicated to Gjallarhorn. In the future I would like to have the WCH send all headers to Gjallarhorn. The wallet will then use the bloom filter to determine if a block is relevant and when relevant transactions are found the WCH will decompose the block body into the constituent transactions queried by the wallet. At this point a transaction witness will be needed to ensure trustless communication between Gjallarhorn and the responding WCH.

**Comment by jingsting** [comment]
WCH is not currently in use, so closing this ticket. No longer applicable
