### ISSUE TITLE
An actor still running when Gjallarhorn shuts down 

### ISSUE THREAD

**Issue by mhalloran21** [Topl/Bifrost#876]
* Gjallarhorn doesn't seem to shutdown on ctrl+c but shuts down on sbt exit

┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-917) by [Unito](https://www.unito.io)

**Comment by jingsting** [comment]
Gjallarhorn is disabled for now. No longer applicable
