### ISSUE TITLE
Akka routing port is being bound multiple times in tests

### ISSUE THREAD

**Issue by Tuxman** [Topl/Bifrost#892]
The Akka routing port for communication between Bifrost and Gjallarhorn is bound every time a new ActorSystem is created. While this is acceptable for a single running instance of Bifrost, the automatic binding is problematic for multiple instances or creating new ActorSystems in the test suite. A better solution would be to upgrade to Akka Cluster and bind the port at runtime in BifrostApp.

**Comment by scasplte2** [comment]
this no longer appears to be an issue. We believe an upgraded dependency or a reorg of the testing process may have resolved the issue.

**Comment by Tuxman** [comment]
This is still an issue for Gjallarhorn, and needs to be resolved to include remoting actors when interfacing between Gjallarhorn and Bifrost.
