### ISSUE TITLE
Gjallarhorn using multi-sig (threshold proposition) 

### ISSUE THREAD

**Issue by mhalloran21** [Topl/Bifrost#900]
┆Issue is synchronized with this [Jira Task](https://topl.atlassian.net/browse/CORE-919) by [Unito](https://www.unito.io)

**Comment by scasplte2** [comment]
This is going to be an involved process including the user story on to communicate to users how to construct the multi-sig proposition and from a technical side to replicate the needed functionality to create a Threshold proposition in the Gjallarhorn back-end.

**Comment by jingsting** [comment]
Superseded by credential library
